apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: fiap-x-dev
data:
  APP_NAME: "FIAP X Authentication Service"
  APP_VERSION: "1.0.0"
  APP_ENVIRONMENT: "production"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  JWT_ALGORITHM: "HS256"
  JWT_ISSUER: "fiap-x-auth"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "30"
  SECURITY_BCRYPT_ROUNDS: "12"
  SECURITY_RATE_LIMIT_REQUESTS: "100"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: video-service-config
  namespace: fiap-x-dev
data:
  APP_NAME: "FIAP X Video Processing Service"
  APP_VERSION: "1.0.0"
  APP_ENVIRONMENT: "production"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8001"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  AUTH_SERVICE_URL: "http://auth-service:8000"
  PROCESSING_MAX_FILE_SIZE_MB: "500"
  PROCESSING_MAX_CONCURRENT_JOBS: "4"
  PROCESSING_FFMPEG_PATH: "ffmpeg"
  PROCESSING_FFPROBE_PATH: "ffprobe"
  STORAGE_BASE_PATH: "/app/storage"
  STORAGE_VIDEO_PATH: "/app/storage/videos"
  STORAGE_FRAMES_PATH: "/app/storage/frames"
  STORAGE_ZIP_PATH: "/app/storage/results"
  STORAGE_TEMP_PATH: "/app/storage/temp"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: fiap-x-dev
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_CFG_LISTENERS: "CLIENT://:29092,EXTERNAL://:9092"
  KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://kafka-service:29092,EXTERNAL://kafka-service:9092"
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "CLIENT"
  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_CFG_NUM_PARTITIONS: "3"
  KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_CFG_LOG_RETENTION_HOURS: "168"
  KAFKA_CFG_LOG_SEGMENT_BYTES: "1073741824"
  KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"