apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: fiap-x-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fiap-x-dev
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-service-sa
      containers:
      - name: auth-service
        image: ${IMAGE_URI}
        ports:
        - containerPort: 8000
        env:
        - name: APP_NAME
          value: "FIAP X Authentication Service"
        - name: APP_VERSION
          value: "1.0.0"
        - name: APP_ENVIRONMENT
          value: "production"
        - name: APP_HOST
          value: "0.0.0.0"
        - name: APP_PORT
          value: "8000"
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: JWT_ISSUER
          value: "fiap-x-auth"
        - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
          value: "15"
        - name: JWT_REFRESH_TOKEN_EXPIRE_DAYS
          value: "30"
        - name: SECURITY_BCRYPT_ROUNDS
          value: "12"
        - name: SECURITY_RATE_LIMIT_REQUESTS
          value: "100"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: DB_SECRET_ARN
          value: "${AUTH_DB_SECRET_ARN}"
        - name: JWT_SECRET_ARN
          value: "${JWT_SECRET_ARN}"
        - name: REDIS_SECRET_ARN
          value: "${REDIS_SECRET_ARN}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fiap-x-dev
spec:
  selector:
    app: auth-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP