apiVersion: v1
kind: ServiceAccount
metadata:
  name: video-service-sa
  namespace: fiap-x-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
  namespace: fiap-x-dev
  labels:
    app: video-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      serviceAccountName: video-service-sa
      containers:
      - name: video-service
        image: ${IMAGE_URI}
        ports:
        - containerPort: 8001
        env:
        - name: APP_NAME
          value: "FIAP X Video Processing Service"
        - name: APP_VERSION
          value: "1.0.0"
        - name: APP_ENVIRONMENT
          value: "production"
        - name: APP_HOST
          value: "0.0.0.0"
        - name: APP_PORT
          value: "8001"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8000"
        - name: PROCESSING_MAX_FILE_SIZE_MB
          value: "500"
        - name: PROCESSING_MAX_CONCURRENT_JOBS
          value: "4"
        - name: STORAGE_BASE_PATH
          value: "/app/storage"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: DB_SECRET_ARN
          value: "${VIDEO_DB_SECRET_ARN}"
        - name: REDIS_SECRET_ARN
          value: "${REDIS_SECRET_ARN}"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: video-storage
          mountPath: /app/storage
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: video-storage
        persistentVolumeClaim:
          claimName: video-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: fiap-x-dev
spec:
  selector:
    app: video-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-storage-pvc
  namespace: fiap-x-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 100Gi