apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: fiap-x-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::720049726178:role/LabRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: video-service-sa
  namespace: fiap-x-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::720049726178:role/LabRole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fiap-x-dev
  name: app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-binding
  namespace: fiap-x-dev
subjects:
- kind: ServiceAccount
  name: auth-service-sa
  namespace: fiap-x-dev
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: video-service-binding
  namespace: fiap-x-dev
subjects:
- kind: ServiceAccount
  name: video-service-sa
  namespace: fiap-x-dev
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io